### ISSUE TITLE
StackOverflowException in new release 1.0.37

### ISSUE THREAD

**Issue by SvenSkrabal** [ooples/OoplesFinance.StockIndicators#16]
If you run the following code on any data:
```
stockData.CalculateRelativeStrengthIndex();
```
There will be an **StackOverflowException**. I tracked it down to the following lines:
```
    /// <summary>
    /// Adds the rounded.
    /// </summary>
    /// <param name="list">The list.</param>
    /// <param name="value">The value.</param>
    public static void AddRounded(this List<decimal> list, decimal value)
    {
        list.AddRounded(Math.Round(value, 4));
    }
```
This must be:
```
    /// <summary>
    /// Adds the rounded.
    /// </summary>
    /// <param name="list">The list.</param>
    /// <param name="value">The value.</param>
    public static void AddRounded(this List<decimal> list, decimal value)
    {
        list.Add(Math.Round(value, 4));
    }
```

**Comment by ooples** [comment]
@SvenSkrabal Don't know how I missed something so obvious but I'm getting a new version published right now

**Comment by ooples** [comment]
@SvenSkrabal Can you confirm for me that the latest release fixes the issue for you? You can download the nuget package

**Comment by SvenSkrabal** [comment]
@ooples Thanks for the fast response! The new release 1.0.38 fixes the reported issue.
Minor suggestion for the future: Add some basic regression/unit tests and run them before every release e.g. check some basic indicators for their output 👍
