### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by claudio-silva** [ooples/OoplesFinance.StockIndicators#17]
Can't find any mention of the open source license anywhere.
Sorry if I missed it.

**Comment by ooples** [comment]
@claudio-silva Sorry about that, I thought I put it on the github repo but don't see it. Anyway it is an Apache 2.0 license and you can get that info here: https://www.nuget.org/packages/OoplesFinance.StockIndicators/

**Comment by ooples** [comment]
@claudio-silva I just did an update to add my open source license and contact info on all pages so go ahead and close this issue if everything looks good now

**Comment by claudio-silva** [comment]
Thank you for your response.

The idea of adding the license to all files was good, but still, it would be better and more in-line with accepted best practices for GitHub if you add a license file to the repo.
It's easy and quick; just follow these steps:
[https://docs.github.com/en/enterprise-cloud@latest/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository]()
That way, it will be easier for anyone to find out which license is being used, the project will appear on searches filtered by license, etc.

As the bare minimum, a mention on the README would be very helpful.

Anyway, I'm glad the license is a good one, so this library may be useful for a small private project I'm working on.
Thank you for publishing it! 👍

**Comment by ooples** [comment]
@claudio-silva So I already changed the readme yesterday so it now reads like this:

This is a stock indicator library that is completely open source (Apache 2.0 license) and very easy to use

Also I did add the license file to the project but apparently spaced out and forgot to do a commit so you should now see the license in the root folder.

**Comment by claudio-silva** [comment]
Great!
Sorry I missed the readme change.
Now I can also see the license on the right sidebar :-) and the license file.
I believe these changes will improve the project's discoverability and credibility a little bit.
Thank you for your quick response.
