### ISSUE TITLE
calculating indicators on the same data set

### ISSUE THREAD

**Issue by pavlexander** [ooples/OoplesFinance.StockIndicators#22]
I would like to be able to create X number of indicators on the same input data. As per documentation I am using the recomended approach by invoking `stockData.Clear();`, however, this method seems to be cleaning up the values of the previous outputted collection _in some cases_ (**bug?**). 

Consider following example:

```cs
            var results = stockData.CalculateBollingerBands();
            var line2 = results.OutputValues["UpperBand"];
            var line3 = results.OutputValues["MiddleBand"];
            var line4 = results.OutputValues["LowerBand"];

            stockData.Clear();
            var results2 = stockData.CalculateMovingAverageV3();
            var line5 = results2.OutputValues["Mav3"];

            stockData.Clear();
            var results3 = stockData.CalculateSimpleMovingAverage();
            var line6 = results3.OutputValues["Sma"];

            stockData.Clear();
```

* upon invoke of `stockData.Clear();` on the BollingerBands results - the values in collection `line2 `, `line3`, `line4`  are not being cleaned up
* upon invoke of the method 2nd and 3rd times - both the `line5` and `line6` are affected by the cleaned up as well..

Why the results of the BollingerBands calculation are not being cleaned, while the rest are?

I do think that there is some kind of bug there, since the behavior is expected to be the same for all scenarios.. Proof:

https://user-images.githubusercontent.com/20644772/199935411-3266fc73-a389-4c91-9f8b-ac633b4326df.mp4

I would like to be able to calculate multiple indicators on the same data set. If the behavior is intended, then how to achieve my goal? (Cloning the resulting list seems to be the temporary solution)

**Comment by ooples** [comment]
@pavlexander I want to apologize for my delay. My wife just gave birth to our twins and I have been at the hospital for awhile now. I can answer your questions once I get back home to my office computer

**Comment by ooples** [comment]
@pavlexander Can you please provide me with the code that you used for the video file so I can take a look?
