### ISSUE TITLE
New Indicator Suggestion: Market Meanness Index

### ISSUE THREAD

**Issue by gcaplan** [ooples/OoplesFinance.StockIndicators#23]
Request to add this very interesting volatility index, based on a fundamental principle of statistics.

The author is a seasoned pro trader and claims it beats most other trend indicators in backtesting.

Only requires half-a-dozen lines of straightforward code. Would do it myself, but new to both C# and Git so a pull request would be a bit of a learning curve. If you can manage to add this in the midst of your new parenthood it would be appreciated!

Explanation here, along with code in C:

[https://financial-hacker.com/the-market-meanness-index/](url)

Thanks for all your hard work producing this comprehensive library!

**Comment by ooples** [comment]
Yeah I will include this in my next version along with a recent request
from another user to change everything to use double by default. Parenting
is definitely hard with two babies but I think I'm finally getting the hang
of it

Franklin

**Comment by gcaplan** [comment]
Many thanks!

**Comment by ooples** [comment]
@gcaplan I just uploaded the latest version and I added the Market Meanness Indicator. Please let me know if there are any bugs or if I made any mistakes but if not then please close this issue.

**Comment by gcaplan** [comment]
All looks good. Many thanks!
