### ISSUE TITLE
Supertrend returning same values

### ISSUE THREAD

**Issue by whatthejay** [ooples/OoplesFinance.StockIndicators#24]
Hi.
Thank you for this great library.

I'm trying to use your library in my project and I installed using nuget.

I'm trying to calculate the Supertrend indicator but it's returning all same values - all items in the OutputList contains same values)
Can you please provide sample code to calculate the Supertrend indicator?

Here's my code snippet:

StockData stockData = new StockData(quotes.Select(x => x.ToTickerData()));
var st = stockData.CalculateSuperTrend(maType: MovingAvgType.ExponentialMovingAverage, length: 10, atrMult: 3.0);

**Comment by ooples** [comment]
Are you able to share any of your code or the ticker data you use so I can
replicate what you are seeing? Also what are the same values you are
getting for the supertrend output?

Franklin

**Comment by whatthejay** [comment]
I'm using data from KRX market and it is the typical OHLCV value data.

Here's the input value:
![image](https://user-images.githubusercontent.com/36028972/208326015-bc767715-5983-4064-8754-7454dc929f0a.png)

and here's the output from the CalculateSuperTrend method:
![image](https://user-images.githubusercontent.com/36028972/208326061-f8f379d7-98bc-4e80-84cc-81246e24c335.png)

**Comment by ooples** [comment]
@whatthejay Just uploaded a new version that fixes the typo I had in my code so can you please confirm that this fixed the issue for you?

**Comment by whatthejay** [comment]
@ooples  Thank you, Franklin. I think it works with the newer version.

**Comment by ooples** [comment]
@whatthejay Alright good to hear! I'm going to close this now but feel free to open it in case you spot any issues. Please let me know if you find any other bugs of course.
