### ISSUE TITLE
Input parameters for SqueezeMomentumIndicator

### ISSUE THREAD

**Issue by whatthejay** [ooples/OoplesFinance.StockIndicators#25]
First of all, thank you for this great library :)

I'm considering using SqueezeMomentumIndicator in your library.

In the LazyBear's implementation, there are some input parameters to calculate Bollinger Bands and Keltner Channels,
but your implementation is missing those parameters.

Are those parameters not relevant to the output of the indicator?

I really appreciate any advise you can provide.

**Comment by ooples** [comment]
@whatthejay Which parameters are you referring to?

**Comment by whatthejay** [comment]
They have 5 parameters:

Bollinger Bands Period (this can be replaced with the current length parameter) and Bollinger Bands multiplier
Keltner Channels Period (same as above) and ATR Multiplier
Also whether to use TrueRange when calculating ATR in Keltner Channels.

The code below is from the pine script of LazyBear's implementation.
==============================================
length = input(20, title='BB Length')
mult = input(2.0, title='BB MultFactor')
lengthKC = input(20, title='KC Length')
multKC = input(1.5, title='KC MultFactor')

useTrueRange = input(true, title='Use TrueRange (KC)')
==============================================

**Comment by ooples** [comment]
@whatthejay So I left out those parameters because they don't affect the actual indicator output and are used just for deciding what color to use for plotting the indicator. I do plan on incorporating my library to work better with charting software and to include colors but this is far down the line for me at the moment.

**Comment by whatthejay** [comment]
Thank you for the clarifying :)
