### ISSUE TITLE
Missing includes in OoplesFinance.StockIndicators.csproj

### ISSUE THREAD

**Issue by jkelin** [ooples/OoplesFinance.StockIndicators#4]
[OoplesFinance.StockIndicators.csproj](https://github.com/ooples/OoplesFinance.StockIndicators/blob/master/OoplesFinance.StockIndicators.csproj#L133) contains references to a missing `Images` folder, reference to `C:\Users\cheat\Downloads\Favicon.jpg` and `<PackageIcon>Favicon.jpg</PackageIcon>`. After removing these I could get it to build. Overall `StockIndicators.csproj` could use some cleaning up.

This is really an impressive project BTW! Where do the indicator implementations come from? Did you write all 510 of them by hand?

**Comment by ooples** [comment]
I'm not sure why I was suddenly having errors with the missing favicon file and I'm still trying to figure that out but you could easily install the library through nuget instead. Thank you very much for your kind words. I wrote all 700 or so indicators by hand and will eventually include all of them in this library. I have been publishing indicators for the last few years on Tradingview and wanted to share my personal library with the world. I will let you know when I have this issue permanently fixed but in the meantime please help spread the word about this library if you can. It is a few weeks old and doesn't have much attention yet.

**Comment by jkelin** [comment]
That is pretty amazing honestly, I can't even imagine the dedication that went into writing so many. I assume that you are porting them by hand from the tradingview syntax?

Just a few months ago I was bemoaning how much value is locked in TV scripts using their proprietary ecosystem and wondering whether it could be machine translated and exported.

Anyway keep up the good work, I'll sure spread the word 👍

**Comment by ooples** [comment]
I only actually ported over around 200 from tv and the rest are either new
indicators written by me or gathered from other sources. I'm sure you can
tell this is my first open source project which is why I'm having so many
strange configuration issues but I will get them ironed out

**Comment by ooples** [comment]
I provided a possible fix for the issue you are having and as a bonus added 38 new indicators. Please let me know if this latest version fixes your issue

**Comment by ooples** [comment]
I'm going to go ahead and close this issue if I don't hear from you within the next few days

**Comment by jkelin** [comment]
Hi, yes this is fixed now, thanks!
